# Save as .codeclimate.yml (note leading .) in project root directory
engines:
  eslint:
    enabled: true
    checks:
      indent:
        enabled: false
      no-underscore-dangle:
        enabled: false

ratings:
   paths:
   - src/**

exclude_paths:
- "ko-component-router.js"
- "ko-component-router.min.js"
- "karma.conf.js"
- "test/*"
